language: node_js
node_js:
  - 0.10
before_install:
  - npm install -g gulp
before_script:
  - rm -rf .gitignore
  - gulp make:dist
deploy:
  provider: heroku
  buildpack: node
  strategy: git
  api_key:
    secure: I1ZnuZxiF7vrBqQ6beviqAWcguZSC8PQClHjLBsQ10XGU5QlL8n3pxUPMpzt/yIT1LH9RSNXgtEgi9584CD7Y9LbFLurfizllyyqSVV7zsLNo8VvFmk8/99k6rbTK8jeOMXPcK81R0TWkXbTeJc91Olo25ma+oPhkQITiHh0bSI=
  app: phaser-game-sandbox
  on:
    repo: jcrapsey/phaser-game-sandbox
  skip_cleanup: true
